version: '3.8'

services:
  book-store:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book-store
    env_file: ./.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:${MYSQL_DB_DOCKER_PORT}/${MYSQLDB_DATABASE}?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ${MYSQLDB_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
      - "${DEBUG_PORT}:${DEBUG_PORT}"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0.33
    container_name: book-store-db
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
    ports:
      - "${MYSQL_LOCAL_PORT}:${MYSQL_DB_DOCKER_PORT}"
    restart: unless-stopped
